name: release-please

on:
  push:
    branches: ["master"]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please-action
        uses: google-github-actions/release-please-action@v3.1.2
        id: release
        with:
          release-type: ruby
          package-name: encrypt_env
          bump-minor-pre-major: true
          version-file: "lib/encrypt_env/version.rb"

      - uses: actions/checkout@v3
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
